import random
from tkinter import *
import tkinter as tk
from PIL import Image, ImageTk

# Very Basic Summary: John made the base code logic, Revy made the image displays, Aysen made keyboard, Everyone was involved in Brainstorming Ideas and Layout
# Credit going forward is given in order of who did the most in the function

WINDOW_WIDTH = 450
WINDOW_HEIGHT = 500

# GLOBAL IMAGE STORAGE (made by Revy)

reactor_images = {}

# WORD BANKS (Generated by Chatgpt)

word_bank_easy = [
   "cat", "dog", "sun", "bed", "hat", "cup", "box", "tree",
   "book", "ball", "bat", "pen", "bag", "car", "door", "fish",
   "milk", "shoe", "star", "moon", "kite", "bird", "cake", "frog",
   "ring", "ship", "farm", "home", "road", "lamp", "bell", "king",
   "queen", "corn", "rice", "chair", "spoon", "phone", "clock",
   "grass", "cloud", "plate", "bread", "cheese", "cookie", "apple",
   "berry", "peach", "grape", "train", "plane", "truck", "river",
   "beach", "table", "pillow", "blanket", "window", "school",
   "street", "flower", "garden", "pizza", "burger"
]
word_bank_medium = [
   "planet", "rocket", "castle", "jungle", "desert", "ocean", "valley", "bridge",
   "forest", "island", "mirror", "pocket", "button", "guitar", "camera", "silver",
   "office", "market", "kitchen", "library", "college", "stadium", "tunnel",
   "ladder", "pillow", "blanket", "driver", "painter", "singer", "actor",
   "writer", "doctor", "farmer", "dancer", "baker", "dragon", "wizard",
   "ranger", "hunter", "boxer", "goalie", "keeper", "striker", "captain",
   "thunder", "lightning", "shadow", "spirit", "secret", "puzzle", "portal",
   "energy", "shield", "hammer", "engine", "random", "remote", "symbol",
   "memory", "gesture", "bottle", "cereal", "glacier", "harvest"
]
word_bank_hard = [
   "labyrinth", "pneumonia", "fluorescent", "psychotherapy", "xylophone",
   "whirlwind", "kryptonite", "quagmire", "zombified", "jackknife",
   "backpack", "mystery", "galaxy", "nebula", "asteroid", "eclipse",
   "tsunami", "horizon", "terminal", "fortress", "avalanche", "blizzard",
   "cyclone", "hurricane", "tornado", "vortex", "triangle", "polygon",
   "equation", "variable", "function", "database", "algorithm", "firewall",
   "password", "joystick", "satellite", "hydrogen", "nitrogen", "oxygen",
   "helium", "neutron", "proton", "isotope", "quantum", "photon",
   "gradient", "integral", "derivative", "matrix", "paradox", "illusion",
   "nightmare", "insomnia", "adrenaline", "caffeine", "knapsack",
   "sapphire", "dynamite", "camouflage", "rhinoceros", "crocodile",
   "chandelier", "orchestra"
]
word_bank_phrases = [
   "break a leg", "once in awhile", "piece of cake", "under the weather",
   "hit the jackpot", "lost for words", "ahead of schedule",
   "back to square one", "down to earth", "easy does it", "on thin ice",
   "spill the beans", "take it easy", "over the moon", "jump the gun",
   "bite the bullet", "bend the rules", "cut to the chase", "break the ice",
   "call it a day", "costs a fortune", "cross your fingers",
   "hit the sack", "on cloud nine", "out of the blue", "pull some strings",
   "rock the boat", "rule of thumb", "throw in the towel", "time flies",
   "under pressure", "up in the air", "word of mouth", "zero tolerance",
   "better late", "burning question", "calm before storm",
   "caught red handed", "change of heart", "crack of dawn",
   "cut corners", "fair and square", "fall from grace", "from scratch",
   "get cold feet", "give me a break", "hold your horses",
   "in the meantime", "jump to conclusions", "keep it simple",
   "let it slide", "living the dream", "make a scene", "miss the point",
   "no hard feelings", "on the same page", "play it safe",
   "raise the bar", "read the room", "second thoughts",
   "silver lining", "speak your mind"
]

word_banks = {
   "easy": word_bank_easy,
   "medium": word_bank_medium,
   "hard": word_bank_hard,
   "phrases": word_bank_phrases
}

# GLOBAL GAME STATE (made by John)

wins = 0
losses = 0
wrong_guess = 0
display_word = []
guessed_letters = []
keyboard_buttons = {}

# CLEAR WINDOW (made by Revy Edited and finished by Revy)

def clear_window():
    for widget in window.winfo_children():
        widget.destroy()

# LOAD IMAGES (made by Revy Edited and finished by Revy)

def load_images():
    global reactor_images, title_screen, loss_screen, win_screen

    # TITLE SCREEN
    title_screen = ImageTk.PhotoImage(
        Image.open("images/title_screen.png").resize((WINDOW_WIDTH, WINDOW_HEIGHT))
    )

    # WIN SCREEN
    win_screen = ImageTk.PhotoImage(
        Image.open("images/win_screen.png").resize((WINDOW_WIDTH, WINDOW_HEIGHT))
    )

    # LOSS SCREEN
    loss_screen = ImageTk.PhotoImage(
        Image.open("images/loss_screen.png").resize((WINDOW_WIDTH, WINDOW_HEIGHT))
    )

    # HANGMAN STAGES
    for stage in range(7):
        img = Image.open(f"images/stage{stage}.png").resize((400, 300))
        reactor_images[stage] = ImageTk.PhotoImage(img)

# DRAW HANGMAN IMAGE (made by Revy finished by Revy)

def draw_hangman(wrong_guess):
    canvas.delete("all")
    stage = max(0, min(wrong_guess, 6))
    img = reactor_images[stage]
    canvas.create_image(200, 150, image=img)
    canvas.image = img

# POPUP MESSAGE (made by John Edited and finished by Revy and John)

def open_popup(keyword, result):
   global wins, losses, reactor_images, window

   clear_window() #Wipes everything in the window

   #displays the background picture whether its win or lose
   bg_label = tk.Label(window, image = result)
   bg_label.place(x = 0, y = 0, relwidth = 1, relheight = 1)


   #Shows win/loss stats and what the keyword was
   keyword_label = tk.Label(window, text = f"Shutdown Code Was:\n{keyword.title()}", font = ("Arial", 12), bg = "#8b8b8b")
   keyword_label.place(relx = 0.5, rely = 0.80, anchor = "center")
   stats_label = tk.Label(window, text = f"Wins: {wins}   Losses: {losses}", font = ("Arial", 12), bg = "#8b8b8b")
   stats_label.place(relx = 0.5, rely = 0.72, anchor = "center")

   #makes the play again and quit buttons
   play_button = tk.Button( window, text = "Play Again", bg = "dark grey", width = 9, height = 2, command = lambda: choose_difficulty())
   play_button.place(relx = 0.40, rely = 0.55, anchor = "center")
   quit_button = tk.Button( window, text = "Quit", bg = "dark grey", width = 9, height = 2, command = window.destroy)
   quit_button.place(relx = 0.60, rely = 0.55, anchor = "center")

# CHOOSE DIFFICULTY (made by John Edited and finished by John and Revy)

def choose_difficulty():
    clear_window()

    if wins + losses >= 1:
        stats_label = tk.Label( window, text=f"{wins} {losses}", font=("Arial", 12), bg="#8b8b8b")
        stats_label.place(relx=0.5, rely=0.72, anchor="center")

    # Load title screen background
    bg_img = Image.open("images/title_screen.png")
    bg_img = bg_img.resize((450, 500))
    bg_photo = ImageTk.PhotoImage(bg_img)

    window.bg_photo = bg_photo

    # displays background image
    bg_label = tk.Label(window, image=bg_photo)
    bg_label.place(x=0, y=0, relwidth=1, relheight=1)

    button_frame = tk.Frame(window, bg="grey", highlightthickness=0)
    button_frame.place(relx=0.5, rely=0.70, anchor="center")

    # makes difficulty buttons
    easy_btn = tk.Button(button_frame,bg="dark grey",activebackground="grey", text="Easy", width=17, command=lambda: start_game("easy"))
    med_btn = tk.Button(button_frame,bg="dark grey",activebackground="grey", text="Medium", width=17, command=lambda: start_game("medium"))
    hard_btn = tk.Button(button_frame,bg="dark grey",activebackground="grey", text="Hard", width=17, command=lambda: start_game("hard"))
    phrase_btn = tk.Button(button_frame,bg="dark grey",activebackground="grey", text="Phrases", width=17, command=lambda: start_game("phrases"))
    random_btn = tk.Button(button_frame,bg="dark grey",activebackground="grey", text="Random", width=17, command=lambda: start_game("random"))

    easy_btn.pack(pady=3)
    med_btn.pack(pady=3)
    hard_btn.pack(pady=3)
    phrase_btn.pack(pady=3)
    random_btn.pack(pady=3)

# START GAME (made by John Edited and finished by John, Revy and Aysen)

def start_game(difficulty):
    global canvas, wrong_guess, display_word, guessed_letters, keyboard_buttons

    # resets the game when started
    wrong_guess = 0
    display_word = []
    guessed_letters = []
    keyboard_buttons = {}

    # gets the keyword
    keyword = get_keyword(difficulty)

    for widget in window.winfo_children():
        widget.destroy()

    canvas = tk.Canvas(window, width=400, height=300)
    canvas.place(relx=0.5, rely=0.3, anchor="center")

    draw_hangman(0)

    # displays
    display_w = tk.StringVar()
    display_w.set(" ".join(display_word))
    display_wrong = tk.StringVar()
    display_wrong.set(" ".join(guessed_letters))

    row = Frame(window, bg="dark grey")
    row.place(relx=0.5, rely=0.68, anchor="center")

    display_word_label = Label(row, bg="dark grey", textvariable=display_w, font=("Arial", 24))
    display_word_label.pack(padx=15)

    guess_label = Label(row, bg="dark grey", text="Enter Code:", font=("Arial", 18))
    guess_label.pack(side="left", padx=22)
    guess = Entry(row)
    guess.pack(side="left")

    submit_guess = Button(row, text="Submit", command=lambda: check_guess(guess, keyword, difficulty, display_w, display_wrong))
    submit_guess.config(bg="light grey", activebackground="light grey")
    submit_guess.pack(side="left", padx=22)

    create_keyboard(keyword, difficulty, display_w, display_wrong)

# GET KEYWORD (made by John, Edited and finished by John)

def get_keyword(difficulty):
    if difficulty == "random":
        difficulty = random.choice(list(word_banks.keys()))

    keyword = random.choice(word_banks[difficulty])

    for ch in keyword:
        if ch == " ":
            display_word.append(" ")
        else:
            display_word.append("_")

    print(keyword)
    return keyword

# CHECK GUESS (made by John, Edited and finished by John, Revy, Aysen)

def check_guess(guess, keyword, choice, display_w, display_wrong):
    global wrong_guess, display_word, guessed_letters, wins, losses

    guessed_letter = guess.get().lower()

    # lets you solve the whole thing and handles misinputs in the entry box
    if len(guessed_letter) != 1 or not guessed_letter.isalpha():
        if guessed_letter == keyword:
            for i, ch in enumerate(keyword):
                display_word[i] = ch
        elif guessed_letter in word_banks[choice]:
            wrong_guess += 6
            draw_hangman(wrong_guess)
    # handles everything else to do with guessing
    else:
        if guessed_letter in keyword:
            for i in range(len(keyword)):
                if guessed_letter == keyword[i]:
                    display_word[i] = guessed_letter
        else:
            guessed_letters.append(guessed_letter)
            wrong_guess += 1
            draw_hangman(wrong_guess)

    display_w.set(" ".join(display_word))
    display_wrong.set(" ".join(guessed_letters))

    guess.delete(0, tk.END)
    # displays win or loss screen
    if wrong_guess >= 6:
        losses += 1
        open_popup(keyword, loss_screen)
    elif "".join(display_word) == keyword:
        wins += 1
        open_popup(keyword, win_screen)

# KEYBOARD (made by Aysen, Edited and Finished by Aysen, John, Revy)

def create_keyboard(keyword, difficulty, display_w, display_wrong, parent=None):
    global keyboard_buttons

    if parent is None:
        parent = window

    keyboard_frame = Frame(parent, bg="dark grey")
    keyboard_frame.place(relx=0.5, rely=0.88, anchor="center")

    rows = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"]
    for r, row_letters in enumerate(rows):
        row_frame = Frame(keyboard_frame)
        row_frame.pack()
        for letter in row_letters:
            btn = Button(
                row_frame,
                text=letter,
                width=4,
                bg="light grey",
                fg="black",
                activebackground="dark grey",
                command=lambda l=letter.lower(): handle_keyboard_guess(l, keyword, difficulty, display_w, display_wrong)
            )
            btn.pack(side="left", padx=2, pady=2)
            keyboard_buttons[letter] = btn

# KEYBOARD GUESS (made by Aysen, Edited and finished by John, Revy, Aysen)

def handle_keyboard_guess(letter, keyword, choice, display_w, display_wrong):
    global wrong_guess, display_word, guessed_letters, keyboard_buttons, wins, losses

    btn = keyboard_buttons.get(letter.upper())

    if letter in guessed_letters or letter in display_word:
        if btn:
            btn.config(state="disabled")
        return

    # makes the buttons green with a correct press
    if letter in keyword:
        for i in range(len(keyword)):
            if keyword[i] == letter:
                display_word[i] = letter
        if btn:
            btn.config(bg="light green", fg="black", disabledforeground="black", state="disabled")
    # makes button permanently pressed and grey when wrong
    else:
        guessed_letters.append(letter)
        wrong_guess += 1
        draw_hangman(wrong_guess)
        if btn:
            btn.config(bg="grey", fg="black", disabledforeground="black", state="disabled", relief="sunken", bd=1.5)

    display_w.set(" ".join(display_word))
    display_wrong.set(" ".join(guessed_letters))

    #displays win or loss screen
    if wrong_guess >= 6:
        losses += 1
        open_popup(keyword, loss_screen)
    elif "".join(display_word) == keyword:
        wins += 1
        open_popup(keyword, win_screen)

# MAIN WINDOW + IMAGE LOAD + STARTUP (made by John, Edited and finished by Revy and John)

window = Tk()
window.geometry("450x500")
window.title("SAVE THE POWER PLANT")
window.resizable(False, False)
window.config(background="dark grey")

load_images()
choose_difficulty()

window.mainloop()